image: gcc

before_script:
  - apt-get update && apt-get install -y fftw3 libfftw3-dev
  - gcc --version
  - lscpu

build:
  stage: build
  script:
    - ./configure
    - make
    - ./configure --enable-openmp
    - make time_SHT test_suite test_rot
  artifacts:
    paths:
      - Makefile
      - libshtns*.a
      - sht_config.h
      - setup.py
      - time_SHT
      - test_suite
      - test_rot
      - shtns.h

test:
  stage: test
  script:
    - ./test_suite
    - ./test_rot
    - ./time_SHT 127 -quickinit -vector -iter=1
    - ./time_SHT 4095 -quickinit -vector -iter=1 -mres=21 
