      INTEGER SHT_NATIVE_LAYOUT
      PARAMETER (SHT_NATIVE_LAYOUT=0)
      INTEGER SHT_THETA_CONTIGUOUS
      PARAMETER (SHT_THETA_CONTIGUOUS=256)
      INTEGER SHT_PHI_CONTIGUOUS
      PARAMETER (SHT_PHI_CONTIGUOUS=512)

      INTEGER SHT_NO_CS_PHASE
      PARAMETER (SHT_NO_CS_PHASE=1024)

      INTEGER SHT_ORTHONORMAL
      PARAMETER (SHT_ORTHONORMAL=0)
      INTEGER SHT_FOURPI
      PARAMETER (SHT_FOURPI=1)
      INTEGER SHT_SCHMIDT
      PARAMETER (SHT_SCHMIDT=2)

      INTEGER SHT_GAUSS
      PARAMETER (SHT_GAUSS=0)
      INTEGER SHT_AUTO
      PARAMETER (SHT_AUTO=1)
      INTEGER SHT_REG_FAST
      PARAMETER (SHT_REG_FAST=2)
      INTEGER SHT_REG_DCT
      PARAMETER (SHT_REG_DCT=3)
      INTEGER SHT_QUICK_INIT
      PARAMETER (SHT_QUICK_INIT=4)
      INTEGER SHT_REG_POLES
      PARAMETER (SHT_REG_POLES=5)
